dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - directory
  - filepath
  - aeson
  - scotty
  - transformers  

library:
  exposed-modules:     Main
  hs-source-dirs:      src
  build-depends:       base >=4.7 && <5
  default-language:    Haskell2010

executables:
  minecraft-dashboard-exe:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - minecraft-dashboard